apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2024-02-22T14:59:12Z"
  generation: 21
  name: pacman
  namespace: argocd
  resourceVersion: "47837"
  uid: 8cfff05c-3512-447b-a05e-fc4c92c2a26a
spec:
  destination:
    namespace: pacman-argo
    server: https://kubernetes.default.svc
  project: default
  source:
    path: pacman/
    repoURL: https://github.com/LuisPeixotoCTW/GitOps
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: argocd
  health:
    status: Healthy
  history:
  - deployStartedAt: "2024-02-22T14:59:24Z"
    deployedAt: "2024-02-22T14:59:24Z"
    id: 0
    revision: 3e5527a0fe85a2fea92d74867352477854dd7220
    source:
      path: pacman/
      repoURL: https://github.com/LuisPeixotoCTW/GitOps
      targetRevision: HEAD
  - deployStartedAt: "2024-02-22T15:00:27Z"
    deployedAt: "2024-02-22T15:00:27Z"
    id: 1
    revision: 3e5527a0fe85a2fea92d74867352477854dd7220
    source:
      path: pacman/
      repoURL: https://github.com/LuisPeixotoCTW/GitOps
      targetRevision: HEAD
  operationState:
    finishedAt: "2024-02-22T15:00:27Z"
    message: successfully synced (all tasks run)
    operation:
      initiatedBy:
        username: admin
      retry: {}
      sync:
        prune: true
        revision: 3e5527a0fe85a2fea92d74867352477854dd7220
        syncOptions:
        - CreateNamespace=true
        syncStrategy:
          hook: {}
    phase: Succeeded
    startedAt: "2024-02-22T15:00:27Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Service
        message: service/pacman unchanged
        name: pacman
        namespace: pacman-argo
        status: Synced
        syncPhase: Sync
        version: v1
      - group: apps
        hookPhase: Running
        kind: Deployment
        message: deployment.apps/pacman unchanged
        name: pacman
        namespace: pacman-argo
        status: Synced
        syncPhase: Sync
        version: v1
      - group: autoscaling
        hookPhase: Running
        kind: HorizontalPodAutoscaler
        message: horizontalpodautoscaler.autoscaling/pacman-hpa configured
        name: pacman-hpa
        namespace: pacman-argo
        status: Synced
        syncPhase: Sync
        version: v2
      - group: networking.k8s.io
        hookPhase: Running
        kind: Ingress
        message: ingress.networking.k8s.io/pacman unchanged
        name: pacman
        namespace: pacman-argo
        status: Synced
        syncPhase: Sync
        version: v1
      revision: 3e5527a0fe85a2fea92d74867352477854dd7220
      source:
        path: pacman/
        repoURL: https://github.com/LuisPeixotoCTW/GitOps
        targetRevision: HEAD
  reconciledAt: "2024-02-22T15:00:27Z"
  resources:
  - health:
      status: Healthy
    kind: Service
    name: pacman
    namespace: pacman-argo
    status: Synced
    version: v1
  - group: apps
    health:
      status: Healthy
    kind: Deployment
    name: pacman
    namespace: pacman-argo
    status: Synced
    version: v1
  - group: autoscaling
    health:
      message: the HPA controller was able to get the target's current scale
      status: Healthy
    kind: HorizontalPodAutoscaler
    name: pacman-hpa
    namespace: pacman-argo
    status: OutOfSync
    version: v2
  - group: networking.k8s.io
    health:
      status: Healthy
    kind: Ingress
    name: pacman
    namespace: pacman-argo
    status: Synced
    version: v1
  sourceType: Directory
  summary:
    externalURLs:
    - http://pacman.local/pacman-path
    images:
    - ghcr.io/arblctw/pacman:2.0
  sync:
    comparedTo:
      destination:
        namespace: pacman-argo
        server: https://kubernetes.default.svc
      source:
        path: pacman/
        repoURL: https://github.com/LuisPeixotoCTW/GitOps
        targetRevision: HEAD
    revision: 3e5527a0fe85a2fea92d74867352477854dd7220
    status: OutOfSync
